### ISSUE TITLE
Latest changes removed isMobile property

### ISSUE THREAD

**Issue by ghost** [tobie/ua-parser#152]
Hi,

The latest PHP changes removed the isMobile result. Is that so by design, and if it is, what is he reason for interest sake?

I have built my app to listen to that property specifically to count stats a bit differently based on the isMobile property.

Regards

**Comment by AbuJunayd** [comment]
Hi, I would like to know if ua-classifier is available now?

This thread is already 2 years old but I couldn't find ua-classifier anywhere so I thought maybe the name has changed?

Or is there any other way with ua-parser to detect a mobile since isMobile() has been removed?

Thanks a lot
