### ISSUE TITLE
Publish the Java Maven artifact in a repository

### ISSUE THREAD

**Issue by java-artisan** [tobie/ua-parser#233]
It would greatly facilitate the usage of UA Parser in Java if the Maven artifact were publicly available in a repository somewhere.

Preferably in Central. Because it would mean Maven will check there by default for a missing UA Parser artifact.

**Comment by smola** [comment]
Would it be posible to publish it to Maven Central? Note that Maven Central is self-contained, so no artifact in Maven Central can depend on an artifact external to Central.

**Comment by acemilio** [comment]
Could you publish it to Maven Central, please?
