### ISSUE TITLE
php version is not working

### ISSUE THREAD

**Issue by pete111** [tobie/ua-parser#392]
Hi I downloaded and uploaded whole ua-parser to my php hosting (php54).
when I try code 

<?php
require_once 'uaparser/php/bin/uaparser.php';
use UAParser\Parser;

$ua = "Mozilla/5.0 (Macintosh; Intel Mac";

$parser = Parser::create();
$result = $parser->parse($ua);

print $result->ua->family;            // Safari
print $result->ua->major;             // 6
print $result->ua->minor;             // 0
print $result->ua->patch;             // 2
print $result->ua->toString();        // Safari 6.0.2
print $result->ua->toVersion();       // 6.0.2

print $result->os->family;            // Mac OS X
print $result->os->major;             // 10
print $result->os->minor;             // 7
print $result->os->patch;             // 5
print $result->os->patchMinor;        // [null]
print $result->os->toString();        // Mac OS X 10.7.5
print $result->os->toVersion();       // 10.7.5

print $result->device->family;        // Other

print $result->toString();            // Safari 6.0.2/Mac OS X 10.7.5
print $result->uaOriginal;            // Mozilla/5.0 (Macintosh; Intel Ma...

it ends with Fatal error: require_once(): Failed opening required '/uaparser/php/bin/../../../../autoload.php' (include_path='.:/usr/php54/lib/php') in /uaparser/php/bin/uaparser.php on line 11

what is wrong with this?

**Comment by Wyuld0** [comment]
Hi,
I am one of numbers who encounter the same kind of issue trying to run ua-parser on a shared apache server (see for example theses comments: http://davidwalsh.name/user-agent-parser#comment-75418).

So, can you provide a composer-less version of demo.php please?
Thanks in advance.
