### ISSUE TITLE
iOS 8 is not recognized

### ISSUE THREAD

**Issue by mgol** [tobie/ua-parser#450]
iOS 8 is not properly recognized by ua-parser. The user agent format changed; compare the iOS7 one:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.5 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53
```

to the iOS8 one:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_10 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B401 Safari/600.1.4
```

Note the OS 10_10 instead of 7_1. You need to look at the number after `Version/`.

**Comment by mzgol** [comment]
This is fixed in iOS 8.3
![screen shot 2015-04-10 at 11 50 30](https://cloud.githubusercontent.com/assets/1758366/7085529/d9adacac-df77-11e4-85c3-510f353e7ac2.png)
