### ISSUE TITLE
Puffin browser is not recognized

### ISSUE THREAD

**Issue by tamarzil** [tobie/ua-parser#456]
http://www.puffinbrowser.com/

from FAQ:
"Puffin/3.7.0IT" is appended at the end of the user agent for Puffin Web Browser. "Puffin" is the keyword. If Puffin is found in the user agent, it is from the Puffin Web Browser.

"3.7.0"is the version number, where 3 is the major version and .7.0 is the minor version.

The rest two letters with 4 possible combinations represent the OS and the device type:
IP: iOS-Phone
IT: iOS-Tablet
AP: Android-Phone
AT: Android-Tablet

**Comment by tpimh** [comment]
This is resolved, should now be closed.

**Comment by Webictbyleo** [comment]
This is already resolved

**Comment by tamarzil** [comment]
Thanks!
