### ISSUE TITLE
Here's a list of bot looking user agent patterns that escaped detection

### ISSUE THREAD

**Issue by tsaylor** [tobie/ua-parser#459]
I noticed a fair amount of bot traffic going through ua-parser undetected, so I found some patterns to identify them and included a secondary filter in my code.  Should these patterns be added to ua-parser itself?

**Obvious user agent patterns**
bot
spider
crawl
scraper
indexer

**Suspicious user agent patterns**
Google-HTTP-Java-Client/*
Java/*
WhatWeb/*
Python-urllib/*
WordPress/*
TLSProber/*
WinHTTP
Icarus6j - (contact: phil@icarus6.com)
Mozilla/5.0 (compatible; Genieo/1.0 http://www.genieo.com/webfilter.html)
facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
Mozilla/5.0 (Windows NT 6.1; rv:6.0) Gecko/20110814 Firefox/6.0 Google favicon

**Comment by phillipmadlan** [comment]
Was this ever patched?

**Comment by bluesmoon** [comment]
@phillipmadlan this project was moved to https://github.com/ua-parser/uap-core so you may want to check there.

**Comment by phillipmadlan** [comment]
I just checked and it looks like these changes are indeed in there. You should probably close this now.
