### ISSUE TITLE
isMobile alternative

### ISSUE THREAD

**Issue by AbuJunayd** [tobie/ua-parser#492]
Hi,

I just commented in that 2-years old thread: https://github.com/tobie/ua-parser/issues/152 
but maybe it's not monitored anymore.

2 years ago isMobile() was removed from ua-parser and it was said that this would be part of the ua-classifier project.

However I can't find ua-classifier anywhere. 

What's the best solution, 2 years after isMobile has been removed from ua-parser, to detect if the page is served to a mobile phone or tablet?

Thanks

**Comment by dmolsen** [comment]
@AbuJunayd -

My ua-classifier project will not be released. While I initially didn't agree with @tobie's decision to remove those attributes I understood the decision better as time moved on. As I worked on it I realized that I wouldn't have time to keep it up. There's a reason commercial products exist in this space ;)

I'll leave it to others to comment on the best solution.

**Comment by AbuJunayd** [comment]
Oh ok... too sad :) 
Thanks anyway for replying.
