### ISSUE TITLE
Desktop browsers return as Other.

### ISSUE THREAD

**Issue by mamoorkhan** [tobie/ua-parser#493]
Using the UAParser for CSharp, when useragents of different desktop browsers are presented to the parser, it correctly identifies the OS and Browser but returns 'Other' as Device type.

**Comment by Ironholds** [comment]
...yes. What do you think it should be doing?

**Comment by mamoorkhan** [comment]
It should be saying as desktop or pc

**Comment by Ironholds** [comment]
And it knows that it's a desktop how? And, PC is a specific model, how?

The entire point of "other" is "the user agent does not include an explicit string identifying the device model, so we can't provide that device model". Desktop browsers don't do that; there's no way to determine if it's a PC, or a Mac, or a netbook, or, as you note, an older phone. The parser can only work from the information that's actually in the user agent.

**Comment by mamoorkhan** [comment]
it can just simply point out that its a PC, simple

**Comment by Ironholds** [comment]
Except the goal is to identify specific device models, not device _classes_, and you haven't explained how it would "simply" do this (or provided example user agents which would allow this information to be extracted, and have a problem).

**Comment by mamoorkhan** [comment]
with the OS classified into device classes

**Comment by Ironholds** [comment]
Except, again, the goal is to identify devices, not device classes, and OS is not uniformly a mapper to the actual hardware.

**Comment by mamoorkhan** [comment]
can you point me in a direction if I want to know the device class too?

**Comment by Ironholds** [comment]
No; there isn't a project for that that I'm aware of. It has been discussed as a future feature but we haven't started work on it yet.

**Comment by mamoorkhan** [comment]
best of luck with that
