### ISSUE TITLE
Wrong detection of Amazon Silk

### ISSUE THREAD

**Issue by MaximeBaldin** [tobie/ua-parser#494]
Hello!
```php
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; en-us; Silk/1.0.143.1-Gen4_11004910) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Safari/533.16 Silk-Accelerated=true
```

This user agent detects as
```php
object(UAParser\Result\Client)#6 (4) {
  ["ua"]=>
  object(UAParser\Result\UserAgent)#7 (4) {
    ["major"]=>
    string(1) "1"
    ["minor"]=>
    string(1) "0"
    ["patch"]=>
    string(3) "143"
    ["family"]=>
    string(11) "Amazon Silk"
  }
  ["os"]=>
  object(UAParser\Result\OperatingSystem)#8 (5) {
    ["major"]=>
    NULL
    ["minor"]=>
    NULL
    ["patch"]=>
    NULL
    ["patchMinor"]=>
    NULL
    ["family"]=>
    string(7) "Android"
  }
  ["device"]=>
  object(UAParser\Result\Device)#9 (3) {
    ["brand"]=>
    string(6) "Amazon"
    ["model"]=>
    string(6) "Kindle"
    ["family"]=>
    string(6) "Kindle"
  }
  ["originalUserAgent"]=>
  string(173) "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; en-us; Silk/1.0.143.1-Gen4_11004910) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Safari/533.16 Silk-Accelerated=true"
}
```

This is probably bug.

**Comment by Ironholds** [comment]
What should it be?

On Wednesday, 28 January 2015, Max Baldin <notifications@github.com> wrote:

> Hello!
>
> Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; en-us; Silk/1.0.143.1-Gen4_11004910) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Sa
>  fari/533.16 Silk-Accelerated=true
>
> This user agent detects as
>
> object(UAParser\Result\Client)#6 (4) {  ["ua"]=>  object(UAParser\Result\UserAgent)#7 (4) {    ["major"]=>    string(1) "1"    ["minor"]=>    string(1) "0"    ["patch"]=>    string(3) "143"    ["family"]=>    string(11) "Amazon Silk"  }  ["os"]=>  object(UAParser\Result\OperatingSystem)#8 (5) {    ["major"]=>    NULL    ["minor"]=>    NULL    ["patch"]=>    NULL    ["patchMinor"]=>    NULL    ["family"]=>    string(7) "Android"  }  ["device"]=>  object(UAParser\Result\Device)#9 (3) {    ["brand"]=>    string(6) "Amazon"    ["model"]=>    string(6) "Kindle"    ["family"]=>    string(6) "Kindle"  }  ["originalUserAgent"]=>  string(173) "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; en-us; Silk/1.0.143.1-Gen4_11004910) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Safari/533.16 Silk-Accelerated=true"}
>
> This is probably bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobie/ua-parser/issues/494>.
>


-- 
Sent from my mobile computing device of Lovecraftian complexity and horror.

**Comment by MaximeBaldin** [comment]
Hmm. Looks like the problem is a bit deeper, that I thought.
I have a lot of logs, that I need to analyze, this user agents has reference to Mac os and at first I thought, that is should be mac.
After some google, I found this issue https://github.com/tobie/ua-parser/issues/127 and don't know what to think
I will take a look into this problem, but maybe someone have any ideas?

**Comment by MaximeBaldin** [comment]
Wow. It's not a bug - http://www.cardinalpath.com/tracking-the-kindle-fires-silk-browser-with-google-analytics/
Closed.
