### ISSUE TITLE
Publish the Java Maven artifact in the maven central repository

### ISSUE THREAD

**Issue by sdboer78** [tobie/ua-parser#495]
Can you please publish this library to the mvn central repository?

**Comment by MaximumDamage** [comment]
+1 
I found an old ticket about this, I could not find the maven dep tho.
Could we have it published or documented? I'm not sure what is required here ...

Cheers

**Comment by fbacchella** [comment]
Hello please publish it.

**Comment by tobie** [comment]
Current repo is here: https://github.com/ua-parser/uap-java. Closing.
