### ISSUE TITLE
Edge Browser not detected

### ISSUE THREAD

**Issue by AHorak** [tobie/ua-parser#504]
UA on Windows 10: 

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by bluesmoon** [comment]
The project has moved here: https://github.com/ua-parser/uap-core please file issues there.  Also, this issue has been fixed: https://github.com/ua-parser/uap-core/issues/72

**Comment by AHorak** [comment]
Is there also a current NuGet Package for /ua-parser/uap-core?

**Comment by bluesmoon** [comment]
I do not know what NuGet is, but if you look at the ua-parser project you might find something: https://github.com/ua-parser/

**Comment by fourpastmidnight** [comment]
Using the c-sharp port via NuGet, I can confirm that this is an issue. Edge is not properly detected (it's probably being detected as Chrome, not Edge.) Because Edge attempts to look like Chrome, Edge detection must come before Chrome detection in the YAML regex files.
