### ISSUE TITLE
Device family is not getting parsed properly

### ISSUE THREAD

**Issue by vinaySimility** [tobie/ua-parser#505]
Consider these user agent strings:
--------------------------------------------
1. Mozilla/5.0 (Linux; Android 4.0.4; LG-E971 Build/IMM76L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.166 Mobile Safari/537.36

Here the device is "LG-E971"
But ua-parser java module returns "LG-$2". So it looks like. $2 variable is not getting replaced by actual String.

This behavior is consistent with many user strings e.g.:
1. Mozilla/5.0 (Linux; Android 4.4.2; SM-N9005 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Mobile Safari/537.36
returns "Samsung $1$2"
2. Mozilla/5.0 (Linux; Android 4.4.4; HTC Desire 620 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36
returns "HTC Desire $2 $3 $4"

**Comment by commenthol** [comment]
Please consider that this project has moved to [ua-parser](https://github.com/ua-parser). 
I think the problem arises from mixing a regexes.yaml file with an unsupported parser version.

**Comment by vinaySimility** [comment]
Thanks for the response. I solved the problem and used it in my local JAR. I will open a pull request for the relevant project.
