### ISSUE TITLE
unit test error

### ISSUE THREAD

**Issue by leeowenowen** [tobie/ua-parser#519]
i run the unit test and it failed, the main reason is lack of loader initialition in `CachingParserTest.initParser`. so i replace
```
  @Before
  public void initParser() throws Exception {
    parser = new CachingParser();
  }
```
with 
```
  @Before
  public void initParser() throws Exception {
    parser = new CachingParser();
    loader = new DefaultResourceLoader();
  }
```
and everything runs ok.  call `super.initParser() `is also ok.

**Comment by commenthol** [comment]
Hi, this repo has moved to https://github.com/ua-parser/. Please check for the latest version there. Thanks.
