### ISSUE TITLE
Mobile BingBot detected as iPhone

### ISSUE THREAD

**Issue by flansch** [tobie/ua-parser#523]
Testing the UA string

_Mozilla/5.0+(iPhone;+CPU+iPhone+OS+7_0+like+Mac+OS+X)+AppleWebKit/537.51.1+(KHTML,+like+Gecko)+Version/7.0+Mobile/11A465+Safari/9537.53+(compatible;+bingbot/2.0;++http://www.bing.com/bingbot.htm)_

results in

Device: _iPhone_
IsSpider: _false_
OS: _Other_
UserAgent: _bingbot 2.0_

For more information on Bing's mobile user agent strings see https://blogs.bing.com/webmaster/2014/11/03/meet-our-mobile-bots/

**Comment by commenthol** [comment]
This project has moved. Please try with the latest release from ua-parser/uap-core and if still present report this issue there.
