### ISSUE TITLE
regex place holder is not working in regex_yaml

### ISSUE THREAD

**Issue by addictedcoder0** [tobie/ua-parser#528]
Did someone test the regex replacement support provided in the parser .

i am using a custom regex for windows 
- regex: '(Windows NT) (\d+).(\d+)'
    os_replacement: 'Windows $2'

but post parsing i am getting " Windows $2" as it is ... it was supposed to give "Windows 10" .

**Comment by commenthol** [comment]
Please note that project has moved. Check Readme.

**Comment by commenthol** [comment]
Please note that project has moved. Check Readme.
